config/routes.rb
Server::Application.routes.draw do
  
  get "sessions/login"

  get "sessions/home"

  get "sessions/profile"

  get "sessions/setting"

  resources :users
  
  get "users/signup"

  get "users/login"

  get "users/logout"

  get "users/delete"

  get "users/edit"

  get "users/forgot_password"

  get "home//Users/shannonbroekhoven/iCY/Other/src/server"

  get "home/index"

  
  match "signup", :to => "users#new"
  match "login", :to => "sessions#login"
  match "logout", :to => "sessions#logout"
  match "home", :to => "sessions#home"
  match "login_attempt", :to => "sessions#login_attempt"
  match "change_pass", :to => "users#change_password"
  match "forgot_password", :to => "users#forgot_password"
  match "GenerateReport", :to => "records#index"
  match "index", :to => "records#index"
  match "pass_help", :to => "users#pass_help"
  match "attempt", :to => "users#forgot_pass_attempt"
  match "profile", :to => "users#show"
  match "users/:id", :to => "users#update"
  
  
  root :to => 'home#index'
  
  

  resources :records

end

app/models/record.rb
class Record < ActiveRecord::Base
  # attr_accessible :title, :body
  set_primary_key :id
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  require "csv"
  layout "index2", :only => [:index]
  before_filter :authenticate_user, :only => [:index]
  protect_from_forgery :except => :create
  # GET /records
  # GET /records.json
  def index
    
    @start_date = Date.parse(params[:start_date][:day] + "/" +
                             params[:start_date][:month]+"/" +
                             params[:start_date][:year]).beginning_of_day.to_time.to_i rescue nil
    @end_date = Date.parse(params[:end_date][:day] + "/" +
                           params[:end_date][:month]+"/" +
                           params[:end_date][:year]).end_of_day.to_time.to_i rescue nil
    opts = {:order => "created_at"}
    opts[:conditions]  = (@start_date.nil? ? "" : "created_at >= to_timestamp(#{@start_date})")
    opts[:conditions] += ((@start_date.nil? || @end_date.nil?) ? "" : " and ")
    opts[:conditions] += (@end_date.nil?   ? "" : "created_at <= to_timestamp(#{@end_date})")
    opts.delete_if {|k,v| v == ""}
    @records = Record.find(:all,opts, :order => "created_at DESC")
    @records.group_by{|s| s.id}
    @record ||= Record.new
    return render @records if request.xhr?
    respond_to do |format|
      format.html
      format.csv
    end
  end
  def search
  end
  
  def export
    @record = Record.new
    @num = 1
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end
  

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    #@records = Record.all
    @record = Record.new 
    @record.datetime = params[:datetime]
    @record.deviceID = params[:deviceID]
    @record.corticosteriods = params[:history]['0']['value']
    @record.anticholinergics = params[:history]['1']['value']
    @record.eyedrops = params[:history]['2']['value']
    @record.diabetes = params[:history]['3']['value']
    @record.hypertension = params[:history]['4']['value']
    @record.glaucoma = params[:history]['5']['value']
    @record.cataracts = params[:history]['6']['value']
    @record.maculardegeneration = params[:history]['7']['value']
    @record.cognitiveimpairment = params[:history]['8']['value']
    @record.glasses = params[:questionnaire]['0']['value']
    @record.magnifier = params[:questionnaire]['1']['value']
    @record.largeprint = params[:questionnaire]['2']['value']
    @record.helpWithMed = params[:questionnaire]['3']['value']
    @record.prescription = params[:questionnaire]['4']['value']
    @record.nonprescription = params[:questionnaire]['5']['value']
    @record.worn = params[:questionnaire]['6']['value']
    @record.glossy = params[:questionnaire]['7']['value']
    @record.time = params[:test][:time]
    @record.userFont = params[:test][:userFont]

    if(params[:history]['9'].nil?)
      @record.other1 = ""
    else 
      if(params[:history]['9']['value'] == "true")
        @record.other1 = params[:history]['9']['name'] end
    end
      
    if(params[:history]['10'].nil?)
      @record.other2 = ""
    else       
      if(params[:history]['10']['value'] == "true")
        @record.other2 = params[:history]['10']['name'] end
    end
      
    if(params[:history]['11'].nil?)
      @record.other3 = ""
    else       
      if(params[:history]['11']['value'] == "true")
        @record.other3 = params[:history]['11']['name'] end
    end   
    
    if(params[:history]['12'].nil?)
      @record.other4 = ""
    else       
      if(params[:history]['12']['value'] == "true")
        @record.other4 = params[:history]['12']['name'] end
    end
      
    if(params[:history]['13'].nil?)
      @record.other5 = ""
    else       
      if(params[:history]['13']['value'] == "true")
        @record.other5 = params[:history]['13']['name'] end
    end
    @record.save

    respond_to do |format|
      if @record.save
        format.json { render json: @record.id }
        format.html { redirect_to @record, notice: 'Record was created successfully.' }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_export.html.erb
<%= form_for :record, :url => {:action => :index}, :remote => true,
	:method => :get, :html => {:id => 'list_records'} do |fs| %>

	<div class="group">
		<%= label_tag :start_date_day, 'Start Date' %>
		<% today = Date.today %>
		<%= select_date (start_date || today - 1.year), :prefix => :start_date,
			:start_year => 2011, :end_year => today.year %>
		<br/>
		<%= label_tag :end_date_day, 'End Date' %>
		<%= select_date (end_date || today), :prefix => :end_date,
			:start_year => 2011, :end_year => today.year %>
	</div>

	<div class="group">
		<%= image_submit_tag("button (3).png") %><br/>
		<% page_url = request.fullpath.gsub('?', '.csv?') %>
		<%= link_to page_url, page_url %>
	</div>
<% end %>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/_record.html.erb
<% if @num.nil?%>
<% @num = 1 %>
<% end %>
<% if @num == 1 %>
<% type = "orig" %>
<%else %>
<% type = "alt" %>
<%end%>
<tr>
	<td class=<%=type%>><%= record.id %></td>
	<td class=<%=type%>><%= record.deviceID %> </td>
	<td class=<%=type%>><%= record.time.to_f / 1000%>s</td>
	<td class=<%=type%>><%= record.glasses %></td>
	<td class=<%=type%>><%= record.magnifier%></td>
	<td class=<%=type%>><%= record.largeprint %></td>
	<td class=<%=type%>><%= record.helpWithMed%></td>
	<td class=<%=type%>><%= record.prescription %></td>
	<td class=<%=type%>><%= record.nonprescription %></td>
	<td class=<%=type%>><%= record.worn %></td>
	<td class=<%=type%>><%= record.glossy %></td>
	<td class=<%=type%>><%= record.userFont %></td>
	<td class=<%=type%>><%= record.corticosteriods %></td>
	<td class=<%=type%>><%= record.anticholinergics %></td>
	<td class=<%=type%>><%= record.eyedrops %></td>
	<td class=<%=type%>><%= record.diabetes %></td>
	<td class=<%=type%>><%= record.hypertension %></td>
	<td class=<%=type%>><%= record.glaucoma %></td>
	<td class=<%=type%>><%= record.cataracts %></td>
	<td class=<%=type%>><%= record.maculardegeneration %></td>
	<td class=<%=type%>><%= record.cognitiveimpairment %></td>
	<td class=<%=type%>><%= record.other1 %></td>
	<td class=<%=type%>><%= record.other2 %></td>
	<td class=<%=type%>><%= record.other3 %></td>
	<td class=<%=type%>><%= record.other4 %></td>
	<td class=<%=type%>><%= record.other5 %></td>
	<td class=<%=type%>><%= record.datetime %></td>
</tr>

<% @num += 1%>
<% @num = @num.modulo 2 %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.csv.erb
<%- headers = [ "Record ID", "Device ID", "Time Taken", "Glasses","Magnifier", "Large Print","Help With Medication","Prescription",
				"Non-Prescription","Worn","Glossy","Font","Corticosteriods", "Anticholinergics","Eyedrops", "Diabetes","Hypertension",
				"Glaucoma","Cataracts","Macular Degenration","Cognitive Impairment","Other1","Other2","Other3","Other4","Other5","Date"] -%>
<%= CSV.generate_line headers %>

<%- @records.each do |rec| -%>
<%- row = [ rec.userID, rec.deviceID, rec.time, rec.glasses, rec.magnifier, rec.largeprint, rec.helpWithMed, rec.prescription, rec.nonprescription,
			rec.worn, rec.glossy, rec.userFont, rec.corticosteriods, rec.anticholinergics, rec.eyedrops, rec.diabetes, rec.hypertension,
			rec.glaucoma, rec.cataracts, rec.maculardegeneration, rec.cognitiveimpairment, rec.other1, rec.other2, rec.other3,
			rec.other4, rec.other5, rec.datetime] -%>
<%=   CSV.generate_line row %>
<%- end -%>

app/views/records/index.html.erb
<% if !request.xhr? %>
	<%= render :partial => 'export', :locals => {:record => @record,:start_date => @start_date, :end_date => @end_date} %>
<% end %>
<br /><br />
<h3>Records</h3>
<table id="search_results">
	<thead>
		<tr><th>Record ID</th><th>Device ID</th><th>Time Taken</th><th>Glasses</th><th>Magnifier</th>
			<th>Large Print</th><th>Help With Medication</th><th>Prescription</th>
			<th>Non-Prescription</th><th>Worn</th></th><th>Glossy</th><th>Font</th><th>Corticosteriods</th><th>Anticholinergics</th>
			<th>Eyedrops</th><th>Diabetes</th><th>Hypertension</th><th>Glaucoma</th><th>Cataracts</th><th>Macular Degenration</th>
			<th>Cognitive Impairment</th><th>Other1</th><th>Other2</th><th>Other3</th><th>Other4</th><th>Other5</th><th>Date</th>
		</tr>
	</thead>
	<tbody>
<% @num = 1 %>
  <%= render @records %> 
	</tbody>
</table>
<%= link_to "All records", "/GenerateReport"%><br />
<%= link_to "Back", "/home"%>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/search.html.erb
<h2>Generate a Report</h2>
<%= form_for :record, :url => {:action => :index}, :remote => true,
	:method => :get, :html => {:id => 'list_records'} do |fs| %>

	<div class="group">
		<%= label_tag :start_date_day, 'Start Date' %>
		<% today = Date.today %>
		<%= select_date (today - 1.year), :prefix => :start_date,
			:start_year => 2011, :end_year => today.year %>
		<br/>
		<%= label_tag :end_date_day, 'End Date' %>
		<%= select_date (today), :prefix => :end_date,
			:start_year => 2011, :end_year => today.year %>
	</div>

	<div class="group">
		<%= fs.submit 'Generate CSV Link' %><br/>
		<% page_url = request.fullpath.gsub('?', '.csv?') %>
		<%= link_to page_url, page_url %>
	</div>
<% end %>